# Generated by Django 4.2.9 on 2026-01-01 02:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Minimum purchase amount for eligibility', max_digits=15)),
                ('min_age', models.IntegerField(default=16, help_text='Minimum age for eligibility', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('purchase_window_days', models.IntegerField(default=3, help_text='Maximum days between purchases to combine')),
                ('exit_deadline_months', models.IntegerField(default=3, help_text='Maximum months after purchase to exit')),
                ('eligible_residence_countries', models.JSONField(default=list, help_text='List of country codes eligible for refund (empty = all except excluded)')),
                ('excluded_residence_countries', models.JSONField(default=list, help_text='List of country codes NOT eligible for refund')),
                ('excluded_categories', models.JSONField(default=list, help_text='Product categories excluded from refund')),
                ('vat_rates', models.JSONField(default=dict, help_text='VAT rates by category, e.g., {"GENERAL": 16.0, "FOOD": 0.0}')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Default VAT rate if category not specified', max_digits=5)),
                ('operator_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Operator fee as percentage of VAT', max_digits=5)),
                ('operator_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed operator fee per form', max_digits=15)),
                ('min_operator_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum operator fee', max_digits=15)),
                ('allowed_refund_methods', models.JSONField(default=list, help_text='Allowed refund methods: CARD, BANK_TRANSFER, MOBILE_MONEY, CASH')),
                ('risk_score_threshold', models.IntegerField(default=70, help_text='Risk score above which control is required')),
                ('high_value_threshold', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Amount above which additional control is required', max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_rulesets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rulesets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rule set',
                'verbose_name_plural': 'rule sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('field', models.CharField(help_text='Field to check: amount, traveler_country, category, etc.', max_length=50)),
                ('operator', models.CharField(help_text='Operator: equals, not_equals, greater_than, less_than, in, not_in', max_length=20)),
                ('value', models.JSONField(help_text='Value to compare against')),
                ('score_impact', models.IntegerField(default=10, help_text='Points to add to risk score if rule matches')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='rules.ruleset')),
            ],
            options={
                'verbose_name': 'risk rule',
                'verbose_name_plural': 'risk rules',
                'ordering': ['ruleset', 'name'],
            },
        ),
    ]
