# Generated by Django 4.2.9 on 2026-01-04 02:15

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code for the category (e.g., ELECTRONICS)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., Électronique)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('icon', models.CharField(default='📦', help_text='Emoji icon for the category', max_length=10)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Default VAT rate for this category', max_digits=5)),
                ('is_eligible_by_default', models.BooleanField(default=True, help_text='Whether this category is eligible for tax free by default')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for use')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display the category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
