# Generated by Django 4.2.9 on 2026-01-12 00:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0002_add_product_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, CDF)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name (e.g., Dollar américain)', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €, FC)', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate: 1 CDF = X of this currency', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('is_base_currency', models.BooleanField(default=False, help_text='Is this the base currency (CDF)?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this currency available for refunds?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['-is_base_currency', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_rate', models.DecimalField(decimal_places=6, help_text='Previous exchange rate', max_digits=20)),
                ('new_rate', models.DecimalField(decimal_places=6, help_text='New exchange rate', max_digits=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the rate change')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rate_changes', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='rules.currency')),
            ],
            options={
                'verbose_name': 'exchange rate history',
                'verbose_name_plural': 'exchange rate histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
