# Generated by Django 4.2.9 on 2026-01-05 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='OutboundNotification',
        ),
        migrations.RenameIndex(
            model_name='outboundnotification',
            new_name='notificatio_user_id_eb79d6_idx',
            old_name='notificatio_user_id_7088ed_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundnotification',
            new_name='notificatio_status_34b982_idx',
            old_name='notificatio_status_9a4505_idx',
        ),
    ]
