# Generated by Django 4.2.9 on 2026-01-06 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refunds', '0001_initial'),
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Créé'), ('ASSIGNED', 'Assigné'), ('REASSIGNED', 'Réassigné'), ('STATUS_CHANGED', 'Statut modifié'), ('PRIORITY_CHANGED', 'Priorité modifiée'), ('ESCALATED', 'Escaladé'), ('MESSAGE_ADDED', 'Message ajouté'), ('ATTACHMENT_ADDED', 'Pièce jointe ajoutée'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé'), ('REOPENED', 'Réouvert')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'historique ticket',
                'verbose_name_plural': 'historiques tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='disputeticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'ticket support', 'verbose_name_plural': 'tickets support'},
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Support agent handling this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='refunds.refund'),
        ),
        migrations.AddField(
            model_name='disputeticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputeticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('NEED_INFO', 'Informations requises'), ('UNDER_REVIEW', 'En révision'), ('ESCALATED', 'Escaladé'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé'), ('REJECTED', 'Rejeté')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='disputeticket',
            name='type',
            field=models.CharField(choices=[('VALIDATION_MISSED', 'Validation manquée'), ('AMOUNT_ERROR', 'Erreur de montant'), ('IDENTITY_ISSUE', "Problème d'identité"), ('REFUND_NOT_RECEIVED', 'Remboursement non reçu'), ('WRONG_REFUND_AMOUNT', 'Montant de remboursement incorrect'), ('TECHNICAL', 'Problème technique'), ('ACCOUNT', 'Problème de compte'), ('MERCHANT', 'Question commerçant'), ('CUSTOMS', 'Question douane'), ('OTHER', 'Autre')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['status', 'priority'], name='disputes_di_status_3be9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['assigned_to', 'status'], name='disputes_di_assigne_e8fac7_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['created_by', 'status'], name='disputes_di_created_6c42c3_idx'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='disputes.disputeticket'),
        ),
    ]
