# Generated by Django 4.2.9 on 2026-01-06 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disputes', '0002_tickethistory_alter_disputeticket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketObserver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ticket_observers', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='disputes.disputeticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'observateur ticket',
                'verbose_name_plural': 'observateurs tickets',
                'ordering': ['-added_at'],
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
