# Generated by Django 4.2.9 on 2026-01-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_add_ticket_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='disputes.disputemessage'),
        ),
    ]
