# Generated by Django 4.2.9 on 2026-01-01 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nom commercial')),
                ('registration_number', models.CharField(max_length=100, verbose_name='Numéro RCCM')),
                ('tax_id', models.CharField(max_length=100, verbose_name='Numéro Impôt (NIF)')),
                ('national_id', models.CharField(blank=True, max_length=100, verbose_name='Numéro Id. Nat.')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('company_phone', models.CharField(max_length=20, verbose_name='Téléphone entreprise')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email entreprise')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Nom de la banque')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de compte')),
                ('mobile_money_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro Mobile Money')),
                ('mobile_money_provider', models.CharField(blank=True, max_length=50, verbose_name='Opérateur Mobile Money')),
                ('business_sector', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('business_description', models.TextField(blank=True, verbose_name="Description de l'activité")),
                ('rccm_document', models.CharField(blank=True, max_length=500, verbose_name='Document RCCM')),
                ('nif_document', models.CharField(blank=True, max_length=500, verbose_name='Document NIF')),
                ('id_nat_document', models.CharField(blank=True, max_length=500, verbose_name='Document Id. Nat.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_merchant_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'merchant registration request',
                'verbose_name_plural': 'merchant registration requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
