# Generated by Django 4.2.9 on 2026-01-01 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merchantregistrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login Verification'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification')], default='LOGIN', max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation_token', to='accounts.merchantregistrationrequest')),
            ],
            options={
                'verbose_name': 'account activation token',
                'verbose_name_plural': 'account activation tokens',
            },
        ),
    ]
