# Generated by Django 4.2.9 on 2026-01-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_merchantregistrationrequest_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantregistrationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_DOCUMENTS', 'Awaiting Documents'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistrationDocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Message de demande')),
                ('documents_requested', models.JSONField(default=list, help_text='Liste des documents/informations demandés', verbose_name='Documents demandés')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('SUBMITTED', 'Documents Submitted'), ('REVIEWED', 'Reviewed by Admin')], default='PENDING', max_length=20)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('merchant_response', models.TextField(blank=True, verbose_name='Réponse du commerçant')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='Notes de révision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='accounts.merchantregistrationrequest')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document request',
                'verbose_name_plural': 'document requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('file_path', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.registrationdocumentrequest')),
            ],
            options={
                'verbose_name': 'registration document',
                'verbose_name_plural': 'registration documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('ADMIN_NOTE', 'Admin Note'), ('DOCUMENT_REQUEST', 'Document Request'), ('MERCHANT_RESPONSE', 'Merchant Response'), ('STATUS_CHANGE', 'Status Change'), ('SYSTEM', 'System Message')], default='ADMIN_NOTE', max_length=30)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('is_internal', models.BooleanField(default=False, help_text='Visible only to admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_comments', to=settings.AUTH_USER_MODEL)),
                ('document_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='accounts.registrationdocumentrequest')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.merchantregistrationrequest')),
            ],
            options={
                'verbose_name': 'registration comment',
                'verbose_name_plural': 'registration comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('REGISTRATION_NEW', 'New Registration'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('DOCUMENT_REQUESTED', 'Documents Requested'), ('DOCUMENT_SUBMITTED', 'Documents Submitted'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
