# Generated by Django 4.2.9 on 2026-01-03 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('accounts', '0006_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outlet_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator (DGI/DGDA)'), ('CUSTOMS_AGENT', 'Customs Agent'), ('MERCHANT', 'Merchant Admin'), ('MERCHANT_EMPLOYEE', 'Merchant Employee'), ('OPERATOR', 'Refund Operator'), ('AUDITOR', 'Auditor'), ('TRAVELER', 'Traveler')], default='TRAVELER', max_length=20),
        ),
        migrations.CreateModel(
            name='MerchantUserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('MERCHANT', 'Admin Commerçant'), ('MERCHANT_EMPLOYEE', 'Employé')], default='MERCHANT_EMPLOYEE', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='merchants.merchant')),
                ('outlet', models.ForeignKey(blank=True, help_text='Required for employees, optional for merchant admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invitations', to='merchants.outlet')),
            ],
            options={
                'verbose_name': 'merchant user invitation',
                'verbose_name_plural': 'merchant user invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
