# Generated by Django 4.2.9 on 2026-01-05 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_customs_agents_module'),
        ('accounts', '0007_add_outlet_id_and_merchant_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsAgentInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='Grade')),
                ('invitation_token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_invitations', to=settings.AUTH_USER_MODEL)),
                ('point_of_exit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invitations', to='customs.pointofexit', verbose_name='Frontière assignée')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation agent douanier',
                'verbose_name_plural': 'invitations agents douaniers',
                'ordering': ['-created_at'],
            },
        ),
    ]
