# Generated by Django 4.2.9 on 2026-01-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customs_agents_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsagentinvitation',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service/Département'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Contact d'urgence"),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tél. urgence'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relation'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name="N° Carte d'identité"),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='nationality',
            field=models.CharField(blank=True, default='CD', max_length=50, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='customsagentinvitation',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province'),
        ),
    ]
