# Generated by Django 4.2.9 on 2026-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_agent_extended_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
