# Generated by Django 4.2.9 on 2026-01-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'system setting',
                'verbose_name_plural': 'system settings',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_NEW', 'New Registration'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('DOCUMENT_REQUESTED', 'Documents Requested'), ('DOCUMENT_SUBMITTED', 'Documents Submitted'), ('GENERAL', 'General Notification'), ('NEW_CONVERSATION', 'New Conversation'), ('NEW_CHAT_MESSAGE', 'New Chat Message'), ('NEW_TICKET', 'New Ticket'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_ESCALATED', 'Ticket Escalated'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('TICKET_MESSAGE', 'New Ticket Message')], default='GENERAL', max_length=30),
        ),
    ]
