# Generated by Django 4.2.9 on 2026-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserinvitation',
            name='point_of_exit_id',
            field=models.UUIDField(blank=True, help_text='Point de sortie assigné pour les opérateurs', null=True),
        ),
    ]
