# Generated by Django 4.2.9 on 2026-01-01 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxfree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfExit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CD', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'point of exit',
                'verbose_name_plural': 'points of exit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('validations_count', models.IntegerField(default=0)),
                ('successful_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('sync_errors', models.JSONField(default=list)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
                ('point_of_exit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to='customs.pointofexit')),
            ],
            options={
                'verbose_name': 'offline sync batch',
                'verbose_name_plural': 'offline sync batches',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomsValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('VALIDATED', 'Validated'), ('REFUSED', 'Refused'), ('CONTROL_REQUIRED', 'Physical Control Required')], max_length=20)),
                ('refusal_reason', models.CharField(blank=True, choices=[('EXPIRED', 'Form Expired'), ('INVALID_DOCUMENTS', 'Invalid Documents'), ('GOODS_NOT_PRESENT', 'Goods Not Present'), ('GOODS_MISMATCH', 'Goods Do Not Match Invoice'), ('TRAVELER_MISMATCH', 'Traveler Identity Mismatch'), ('ALREADY_VALIDATED', 'Already Validated'), ('SUSPECTED_FRAUD', 'Suspected Fraud'), ('OTHER', 'Other')], max_length=30)),
                ('refusal_details', models.TextField(blank=True)),
                ('physical_control_done', models.BooleanField(default=False)),
                ('control_notes', models.TextField(blank=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('offline_batch_id', models.CharField(blank=True, max_length=50)),
                ('offline_timestamp', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to=settings.AUTH_USER_MODEL)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customs_validation', to='taxfree.taxfreeform')),
                ('point_of_exit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='customs.pointofexit')),
            ],
            options={
                'verbose_name': 'customs validation',
                'verbose_name_plural': 'customs validations',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['decided_at'], name='customs_cus_decided_85a646_idx'), models.Index(fields=['offline_batch_id'], name='customs_cus_offline_b9019c_idx')],
            },
        ),
    ]
