# Generated by Django 4.2.9 on 2026-01-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofexit',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='daily_capacity',
            field=models.IntegerField(default=0, verbose_name='Capacité journalière'),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='is_24h',
            field=models.BooleanField(default=False, verbose_name='Ouvert 24h/24'),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name="Heures d'ouverture"),
        ),
        migrations.AddField(
            model_name='pointofexit',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pointofexit',
            name='type',
            field=models.CharField(choices=[('AIRPORT', 'Aéroport'), ('LAND_BORDER', 'Frontière terrestre'), ('PORT', 'Port maritime/fluvial'), ('RAIL', 'Gare ferroviaire')], default='LAND_BORDER', max_length=20),
        ),
    ]
