# Generated by Django 4.2.9 on 2026-01-05 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customs', '0002_customs_agents_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'En service'), ('PAUSED', 'En pause'), ('ENDED', 'Terminé')], default='ACTIVE', max_length=10)),
                ('total_pause_duration', models.DurationField(default='0:00:00')),
                ('last_pause_at', models.DateTimeField(blank=True, null=True)),
                ('validations_count', models.IntegerField(default=0)),
                ('validated_count', models.IntegerField(default=0)),
                ('refused_count', models.IntegerField(default=0)),
                ('total_amount_validated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('end_notes', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('point_of_exit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='customs.pointofexit')),
            ],
            options={
                'verbose_name': 'agent shift',
                'verbose_name_plural': 'agent shifts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent', 'started_at'], name='customs_age_agent_i_e4496d_idx'), models.Index(fields=['point_of_exit', 'started_at'], name='customs_age_point_o_251737_idx'), models.Index(fields=['status'], name='customs_age_status_9241ac_idx')],
            },
        ),
    ]
