# Generated by Django 4.2.9 on 2026-01-05 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0003_add_agent_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentshift',
            name='total_pause_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
