# Generated by Django 4.2.9 on 2026-01-06 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('taxfree', '0005_rename_taxfree_sta_form_id_a1b2c3_idx_taxfree_sta_form_id_3e9b1f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., heroicon name)', max_length=50)),
                ('target_roles', models.JSONField(default=list, help_text='List of roles that can access this category: ADMIN, MERCHANT, CUSTOMS_AGENT, OPERATOR, AUDITOR')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catégorie de formation',
                'verbose_name_plural': 'catégories de formation',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Article'), ('GUIDE', 'Guide pas-à-pas'), ('VIDEO', 'Tutoriel vidéo'), ('FAQ', 'FAQ')], default='ARTICLE', max_length=20)),
                ('body', models.TextField(blank=True, help_text='HTML or Markdown content')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('video_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('target_roles', models.JSONField(default=list, help_text='List of roles that can access this content')),
                ('related_feature', models.CharField(blank=True, help_text='Feature code for contextual display (e.g., "forms.create", "customs.validate")', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='training/thumbnails/')),
                ('reading_time', models.IntegerField(blank=True, help_text='Estimated reading time in minutes', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_contents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='support.trainingcategory')),
            ],
            options={
                'verbose_name': 'contenu de formation',
                'verbose_name_plural': 'contenus de formation',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'Question générale'), ('TECHNICAL', 'Problème technique'), ('FORM', 'Bordereau Tax Free'), ('REFUND', 'Remboursement'), ('ACCOUNT', 'Compte utilisateur'), ('MERCHANT', 'Commerçant'), ('CUSTOMS', 'Douane'), ('OTHER', 'Autre')], default='GENERAL', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('WAITING_USER', 'En attente utilisateur'), ('WAITING_SUPPORT', 'En attente support'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('unread_by_user', models.IntegerField(default=0)),
                ('unread_by_support', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Support agent handling this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('related_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='taxfree.taxfreeform')),
                ('related_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_from_support', models.BooleanField(default=False, help_text='True if message is from support team')),
                ('is_system_message', models.BooleanField(default=False, help_text='True for automated system messages')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.chatmessage')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('last_position', models.IntegerField(default=0, help_text='Last video position in seconds')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='support.trainingcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression formation',
                'verbose_name_plural': 'progressions formation',
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.AddIndex(
            model_name='trainingcontent',
            index=models.Index(fields=['is_published', 'content_type'], name='support_tra_is_publ_262d83_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcontent',
            index=models.Index(fields=['related_feature'], name='support_tra_related_fa51aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingcontent',
            unique_together={('category', 'slug')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='support_con_user_id_bed716_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_to', 'status'], name='support_con_assigne_930c15_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-last_message_at'], name='support_con_status_7021a0_idx'),
        ),
    ]
