# Generated by Django 4.2.9 on 2026-01-01 02:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxfree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='VAT amount before fees', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('operator_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to traveler', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('method', models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash at Counter')], max_length=20)),
                ('payment_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cash_collected', models.BooleanField(default=False)),
                ('cash_collected_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_refunds', to=settings.AUTH_USER_MODEL)),
                ('cash_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_refunds_processed', to=settings.AUTH_USER_MODEL)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='taxfree.taxfreeform')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_request_id', models.CharField(blank=True, max_length=100)),
                ('provider_response_id', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='refunds.refund')),
            ],
            options={
                'verbose_name': 'payment attempt',
                'verbose_name_plural': 'payment attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='refunds_ref_status_4bb841_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['next_retry_at'], name='refunds_ref_next_re_b3179c_idx'),
        ),
    ]
