# Generated by Django 4.2.9 on 2026-01-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='exchange_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate applied at time of refund (1 CDF = X payout_currency)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to traveler in payout_currency', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='payout_currency',
            field=models.CharField(default='CDF', help_text='Currency in which the refund was paid to traveler', max_length=3),
        ),
    ]
