# Generated by Django 4.2.9 on 2026-01-12 00:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refund_exchange_rate_applied_refund_payout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='actual_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount given to traveler (may be less than payout_amount)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='service_gain',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between payout_amount and actual_payout_amount (rounding gain)', max_digits=15),
        ),
        migrations.AddField(
            model_name='refund',
            name='service_gain_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service gain converted to CDF for reporting', max_digits=15),
        ),
    ]
