# Generated by Django 4.2.9 on 2026-01-01 02:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_number_hash', models.CharField(max_length=64)),
                ('passport_number_last4', models.CharField(max_length=4)),
                ('passport_country', models.CharField(max_length=2)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=2)),
                ('residence_country', models.CharField(max_length=2)),
                ('residence_address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_refund_method', models.CharField(blank=True, max_length=50)),
                ('refund_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'traveler',
                'verbose_name_plural': 'travelers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFreeForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('eligible_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='VAT amount minus operator fees', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('operator_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ISSUED', 'Issued/Printed'), ('VALIDATION_PENDING', 'Pending Customs Validation'), ('VALIDATED', 'Validated by Customs'), ('REFUSED', 'Refused by Customs'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('qr_payload', models.TextField(blank=True)),
                ('qr_signature', models.CharField(blank=True, max_length=64)),
                ('rule_snapshot', models.JSONField(default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_flags', models.JSONField(default=list)),
                ('requires_control', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_forms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='taxfree_form', to='sales.saleinvoice')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxfree_forms', to='taxfree.traveler')),
            ],
            options={
                'verbose_name': 'tax free form',
                'verbose_name_plural': 'tax free forms',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form_number'], name='taxfree_tax_form_nu_f3ca8f_idx'), models.Index(fields=['status'], name='taxfree_tax_status_59e484_idx'), models.Index(fields=['expires_at'], name='taxfree_tax_expires_b7ca3f_idx')],
            },
        ),
    ]
