# Generated by Django 4.2.9 on 2026-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxfree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
