# Generated by Django 4.2.9 on 2026-01-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxfree', '0002_add_passport_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='passport_number_full',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
