# Generated by Django 4.2.9 on 2026-01-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxfree', '0004_statusoverride'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statusoverride',
            new_name='taxfree_sta_form_id_3e9b1f_idx',
            old_name='taxfree_sta_form_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='statusoverride',
            new_name='taxfree_sta_perform_4bc449_idx',
            old_name='taxfree_sta_perform_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='taxfreeform',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Création'), ('ISSUED', 'Émis'), ('VALIDATION_PENDING', 'En attente de validation'), ('VALIDATED', 'Validé par la douane'), ('REFUNDED', 'Remboursé'), ('REFUSED', 'Refusé par la douane'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='CREATED', max_length=20),
        ),
    ]
