# Generated by Django 4.2.9 on 2026-01-01 02:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='merchants.merchant')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='merchants.outlet')),
            ],
            options={
                'verbose_name': 'sale invoice',
                'verbose_name_plural': 'sale invoices',
                'ordering': ['-created_at'],
                'unique_together': {('merchant', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(choices=[('GENERAL', 'General Merchandise'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing & Accessories'), ('JEWELRY', 'Jewelry & Watches'), ('COSMETICS', 'Cosmetics & Perfumes'), ('FOOD', 'Food & Beverages'), ('TOBACCO', 'Tobacco Products'), ('ALCOHOL', 'Alcoholic Beverages'), ('SERVICES', 'Services'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='VAT rate as percentage (e.g., 16.00 for 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_eligible', models.BooleanField(default=True, help_text='Whether this item is eligible for tax refund')),
                ('ineligibility_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleinvoice')),
            ],
            options={
                'verbose_name': 'sale item',
                'verbose_name_plural': 'sale items',
                'ordering': ['created_at'],
            },
        ),
    ]
