# Generated by Django 4.2.9 on 2026-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product_category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
    ]
