# Generated by Django 4.2.9 on 2026-01-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_change_product_category_to_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Code-barres du produit (EAN, UPC, etc.)', max_length=50),
        ),
    ]
